/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { IERC20LikeContract } from "./IERC20Like";
import { ITokenVestingContract } from "./ITokenVesting";
import { MockERC20Contract } from "./MockERC20";
import { TokenVestingContract } from "./TokenVesting";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "IERC20Like"): IERC20LikeContract;
      require(name: "ITokenVesting"): ITokenVestingContract;
      require(name: "MockERC20"): MockERC20Contract;
      require(name: "TokenVesting"): TokenVestingContract;
    }
  }
}

export { IERC20LikeContract, IERC20LikeInstance } from "./IERC20Like";
export { ITokenVestingContract, ITokenVestingInstance } from "./ITokenVesting";
export { MockERC20Contract, MockERC20Instance } from "./MockERC20";
export { TokenVestingContract, TokenVestingInstance } from "./TokenVesting";
