/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ToyContract } from "./Toy";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Toy"): ToyContract;
    }
  }
}

export { ToyContract, ToyInstance } from "./Toy";
